workspace(name = "mvukov_rules_ros2_sample")

new_local_repository(
    name = "pcl",
    path = "/usr",
    build_file_content = """
cc_library(
    name = "pcl",
    hdrs = glob(["include/pcl-1.12/**"]),
    includes = ["include/pcl-1.12"],
    srcs = glob(["lib/x86_64-linux-gnu/libpcl_*.so"]),
    visibility = ["//visibility:public"],
)
    """,
)

new_local_repository(
    name = "eigen",
    path = "/usr/include/eigen3",
    build_file_content = """
cc_library(
    name = "eigen",
    hdrs = glob(["**"]),
    includes = ["."],
    visibility = ["//visibility:public"],
)
    """,
)
