workspace(name = "mvukov_rules_ros2_sample")

new_local_repository(
    name = "pcl",
    path = "/usr",
    build_file_content = """
cc_library(
    name = "pcl",
    hdrs = glob(["include/pcl-1.12/**"]),
    includes = ["include/pcl-1.12"],
    srcs = glob(["lib/x86_64-linux-gnu/libpcl_*.so"]),
    visibility = ["//visibility:public"],
)
    """,
)

new_local_repository(
    name = "eigen",
    path = "/usr/include/eigen3",
    build_file_content = """
cc_library(
    name = "eigen",
    hdrs = glob(["**"]),
    includes = ["."],
    visibility = ["//visibility:public"],
)
    """,
)

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "ros2_pcl_conversions",
    build_file = "//repositories:pcl_conversions.BUILD.bazel",
    sha256 = "018f1ceae604cae9e9beb1bbae31e79052f35c71bbbcedcf5adb44aaaf4aedab",
    strip_prefix = "perception_pcl-2.4.5",
    urls = ["https://github.com/ros-perception/perception_pcl/archive/refs/tags/2.4.5.tar.gz"],
)

http_archive(
    name = "ros2_pcl_msgs",
    build_file = "//repositories:pcl_msgs.BUILD.bazel",
    sha256 = "9a3256d5bd44a2e99526c5cf4ed16198471d2b43c63be74a5fcf8d0dcbb29489",
    strip_prefix = "pcl_msgs-1.0.0",
    urls = ["https://github.com/ros-perception/pcl_msgs/archive/refs/tags/1.0.0.tar.gz"],
)
