workspace(name = "apexai_rules_ros_sample")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load("@bazel_tools//tools/build_defs/repo:local.bzl", "new_local_repository")

# Mock python_interpreter for rules_ros
new_local_repository(
    name = "python_interpreter",
    path = ".",
    build_file_content = "exports_files(['defs.bzl', 'python3'])",
)

# rules_python
http_archive(
    name = "rules_python",
    sha256 = "9c6e26911a79fbf510a8f06d8eedb40f412023cf7fa6d1461def27116bff022c",
    strip_prefix = "rules_python-1.1.0",
    url = "https://github.com/bazelbuild/rules_python/releases/download/1.1.0/rules_python-1.1.0.tar.gz",
)

# rules_ros
http_archive(
    name = "rules_ros",
    strip_prefix = "rules_ros-ee9ebaa0b33a0560c99c22f14d8c178a534f3637",
    urls = ["https://github.com/ApexAI/rules_ros/archive/ee9ebaa0b33a0560c99c22f14d8c178a534f3637.tar.gz"],
)

load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()

# Configure ROS 2 Humble
load("@rules_ros//repos/config:defs.bzl", "configure_ros2")
configure_ros2(distro = "humble")

load("@ros2_config//:setup.bzl", "setup")
setup()

load("@rules_ros//thirdparty:setup_01.bzl", "setup_01")
setup_01()

load("@rules_ros//thirdparty:setup_02.bzl", "setup_02")
setup_02()

load("@rules_ros//thirdparty:setup_03.bzl", "setup_03")
setup_03()

load("@rules_ros//thirdparty:setup_04.bzl", "setup_04")
setup_04()
