cc_binary(
    name = "pcl_sample_node",
    srcs = ["src/pcl_sample_node.cpp"],
    copts = ["-std=c++17"],
    deps = [
        "@ros2//:ros2",
        "@pcl//:pcl",
        "@eigen//:eigen",
    ],
)
